light:
  - platform: serial_send
    name: "Test light"
    serial_port: "/dev/pts/6"
    serial_cmd_turn_on: "68 65 6C 6C 6F"
    serial_cmd_turn_off: "62 79 65"

cover:
  - platform: serial_send
    name: "Test cover"
    serial_port: "/dev/pts/6"
    serial_cmd_start_open: "5B 73 74 61 72 74 5F 6F 70 65 6E 5D"
    serial_cmd_end_open: "5B 65 6E 64 5F 6F 70 65 6E 5D"
    serial_cmd_interval_ms: 3000
    serial_cmd_start_close: "5B 73 74 61 72 74 5F 63 6C 6F 73 65 5D"
    serial_cmd_end_close: "5B 65 6E 64 5F 63 6C 6F 73 65 5D"